services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ab
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "redis:6379", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:ab@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379

volumes:
  data-volume:
